export enum LoanApplicationStatus {
  DRAFT = 'DRAFT',
  PROCESSING_SIMULATION = 'PROCESSING_SIMULATION',
  OFFER_GENERATED = 'OFFER_GENERATED',
  REJECTED = 'REJECTED',
  PENDING_VALIDATION = 'PENDING_VALIDATION',
  COMPLETED = 'COMPLETED',
  ABANDONED = 'ABANDONED',
}
